// Generated by Supabase (supabase gen types typescript).
// Project: pzwdrrjtvabosyqvsvvu. Do not edit by hand — regenerate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      areas: {
        Row: {
          city_id: string;
          created_at: string;
          id: string;
          is_active: boolean;
          name_ar: string;
          name_en: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          city_id: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name_ar: string;
          name_en: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          city_id?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name_ar?: string;
          name_en?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "areas_city_id_fkey";
            columns: ["city_id"];
            isOneToOne: false;
            referencedRelation: "cities";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          action: string;
          actor_id: string | null;
          created_at: string;
          id: string;
          new_data: Json | null;
          old_data: Json | null;
          record_id: string | null;
          table_name: string;
        };
        Insert: {
          action: string;
          actor_id?: string | null;
          created_at?: string;
          id?: string;
          new_data?: Json | null;
          old_data?: Json | null;
          record_id?: string | null;
          table_name: string;
        };
        Update: {
          action?: string;
          actor_id?: string | null;
          created_at?: string;
          id?: string;
          new_data?: Json | null;
          old_data?: Json | null;
          record_id?: string | null;
          table_name?: string;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          description_ar: string | null;
          description_en: string | null;
          icon: string | null;
          id: string;
          image_url: string | null;
          is_active: boolean;
          name_ar: string;
          name_en: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          icon?: string | null;
          id?: string;
          image_url?: string | null;
          is_active?: boolean;
          name_ar: string;
          name_en: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          icon?: string | null;
          id?: string;
          image_url?: string | null;
          is_active?: boolean;
          name_ar?: string;
          name_en?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      cities: {
        Row: {
          code: string;
          created_at: string;
          id: string;
          is_active: boolean;
          name_ar: string;
          name_en: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name_ar: string;
          name_en: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          name_ar?: string;
          name_en?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          created_at: string;
          customer_id: string;
          id: string;
          last_message_at: string | null;
          order_id: string | null;
          provider_id: string;
          quote_request_id: string | null;
          status: Database["public"]["Enums"]["conversation_status"];
          subject: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          customer_id: string;
          id?: string;
          last_message_at?: string | null;
          order_id?: string | null;
          provider_id: string;
          quote_request_id?: string | null;
          status?: Database["public"]["Enums"]["conversation_status"];
          subject?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          customer_id?: string;
          id?: string;
          last_message_at?: string | null;
          order_id?: string | null;
          provider_id?: string;
          quote_request_id?: string | null;
          status?: Database["public"]["Enums"]["conversation_status"];
          subject?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "conversations_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversations_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversations_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "conversations_quote_request_id_fkey";
            columns: ["quote_request_id"];
            isOneToOne: false;
            referencedRelation: "quote_requests";
            referencedColumns: ["id"];
          },
        ];
      };
      coupons: {
        Row: {
          code: string;
          created_at: string;
          deleted_at: string | null;
          ends_at: string | null;
          id: string;
          max_discount: number | null;
          min_order_amount: number | null;
          per_user_limit: number | null;
          provider_id: string | null;
          starts_at: string;
          status: Database["public"]["Enums"]["coupon_status"];
          type: Database["public"]["Enums"]["discount_type"];
          updated_at: string;
          usage_count: number;
          usage_limit: number | null;
          value: number;
        };
        Insert: {
          code: string;
          created_at?: string;
          deleted_at?: string | null;
          ends_at?: string | null;
          id?: string;
          max_discount?: number | null;
          min_order_amount?: number | null;
          per_user_limit?: number | null;
          provider_id?: string | null;
          starts_at?: string;
          status?: Database["public"]["Enums"]["coupon_status"];
          type: Database["public"]["Enums"]["discount_type"];
          updated_at?: string;
          usage_count?: number;
          usage_limit?: number | null;
          value: number;
        };
        Update: {
          code?: string;
          created_at?: string;
          deleted_at?: string | null;
          ends_at?: string | null;
          id?: string;
          max_discount?: number | null;
          min_order_amount?: number | null;
          per_user_limit?: number | null;
          provider_id?: string | null;
          starts_at?: string;
          status?: Database["public"]["Enums"]["coupon_status"];
          type?: Database["public"]["Enums"]["discount_type"];
          updated_at?: string;
          usage_count?: number;
          usage_limit?: number | null;
          value?: number;
        };
        Relationships: [
          {
            foreignKeyName: "coupons_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
        ];
      };
      favorites: {
        Row: {
          created_at: string;
          id: string;
          provider_id: string | null;
          service_id: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          provider_id?: string | null;
          service_id?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          provider_id?: string | null;
          service_id?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "favorites_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "favorites_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "favorites_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      messages: {
        Row: {
          attachments: Json;
          body: string | null;
          conversation_id: string;
          created_at: string;
          deleted_at: string | null;
          id: string;
          is_read: boolean;
          read_at: string | null;
          sender_id: string;
        };
        Insert: {
          attachments?: Json;
          body?: string | null;
          conversation_id: string;
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          is_read?: boolean;
          read_at?: string | null;
          sender_id: string;
        };
        Update: {
          attachments?: Json;
          body?: string | null;
          conversation_id?: string;
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          is_read?: boolean;
          read_at?: string | null;
          sender_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey";
            columns: ["conversation_id"];
            isOneToOne: false;
            referencedRelation: "conversations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "messages_sender_id_fkey";
            columns: ["sender_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          body_ar: string | null;
          body_en: string | null;
          channel: Database["public"]["Enums"]["notification_channel"];
          created_at: string;
          data: Json;
          id: string;
          is_read: boolean;
          read_at: string | null;
          title_ar: string;
          title_en: string;
          type: Database["public"]["Enums"]["notification_type"];
          user_id: string;
        };
        Insert: {
          body_ar?: string | null;
          body_en?: string | null;
          channel?: Database["public"]["Enums"]["notification_channel"];
          created_at?: string;
          data?: Json;
          id?: string;
          is_read?: boolean;
          read_at?: string | null;
          title_ar: string;
          title_en: string;
          type: Database["public"]["Enums"]["notification_type"];
          user_id: string;
        };
        Update: {
          body_ar?: string | null;
          body_en?: string | null;
          channel?: Database["public"]["Enums"]["notification_channel"];
          created_at?: string;
          data?: Json;
          id?: string;
          is_read?: boolean;
          read_at?: string | null;
          title_ar?: string;
          title_en?: string;
          type?: Database["public"]["Enums"]["notification_type"];
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      offers: {
        Row: {
          created_at: string;
          currency: string;
          deleted_at: string | null;
          description_ar: string | null;
          description_en: string | null;
          discount_type: Database["public"]["Enums"]["discount_type"];
          discount_value: number;
          ends_at: string | null;
          final_price: number | null;
          id: string;
          max_redemptions: number | null;
          original_price: number | null;
          provider_id: string;
          redemptions_count: number;
          service_id: string | null;
          starts_at: string;
          status: Database["public"]["Enums"]["offer_status"];
          title_ar: string;
          title_en: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          discount_type: Database["public"]["Enums"]["discount_type"];
          discount_value: number;
          ends_at?: string | null;
          final_price?: number | null;
          id?: string;
          max_redemptions?: number | null;
          original_price?: number | null;
          provider_id: string;
          redemptions_count?: number;
          service_id?: string | null;
          starts_at?: string;
          status?: Database["public"]["Enums"]["offer_status"];
          title_ar: string;
          title_en: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          discount_type?: Database["public"]["Enums"]["discount_type"];
          discount_value?: number;
          ends_at?: string | null;
          final_price?: number | null;
          id?: string;
          max_redemptions?: number | null;
          original_price?: number | null;
          provider_id?: string;
          redemptions_count?: number;
          service_id?: string | null;
          starts_at?: string;
          status?: Database["public"]["Enums"]["offer_status"];
          title_ar?: string;
          title_en?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "offers_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      order_status_history: {
        Row: {
          changed_by: string | null;
          created_at: string;
          from_status: Database["public"]["Enums"]["order_status"] | null;
          id: string;
          note: string | null;
          order_id: string;
          to_status: Database["public"]["Enums"]["order_status"];
        };
        Insert: {
          changed_by?: string | null;
          created_at?: string;
          from_status?: Database["public"]["Enums"]["order_status"] | null;
          id?: string;
          note?: string | null;
          order_id: string;
          to_status: Database["public"]["Enums"]["order_status"];
        };
        Update: {
          changed_by?: string | null;
          created_at?: string;
          from_status?: Database["public"]["Enums"]["order_status"] | null;
          id?: string;
          note?: string | null;
          order_id?: string;
          to_status?: Database["public"]["Enums"]["order_status"];
        };
        Relationships: [
          {
            foreignKeyName: "order_status_history_changed_by_fkey";
            columns: ["changed_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "order_status_history_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          address: string | null;
          area_id: string | null;
          cancelled_at: string | null;
          cancelled_reason: string | null;
          city_id: string | null;
          commission_amount: number;
          completed_at: string | null;
          created_at: string;
          currency: string;
          customer_id: string;
          deleted_at: string | null;
          discount_amount: number;
          id: string;
          notes: string | null;
          offer_id: string | null;
          order_number: string;
          provider_id: string;
          provider_quote_id: string | null;
          scheduled_at: string | null;
          service_id: string | null;
          status: Database["public"]["Enums"]["order_status"];
          subtotal: number;
          tax_amount: number;
          total_amount: number;
          updated_at: string;
        };
        Insert: {
          address?: string | null;
          area_id?: string | null;
          cancelled_at?: string | null;
          cancelled_reason?: string | null;
          city_id?: string | null;
          commission_amount?: number;
          completed_at?: string | null;
          created_at?: string;
          currency?: string;
          customer_id: string;
          deleted_at?: string | null;
          discount_amount?: number;
          id?: string;
          notes?: string | null;
          offer_id?: string | null;
          order_number?: string;
          provider_id: string;
          provider_quote_id?: string | null;
          scheduled_at?: string | null;
          service_id?: string | null;
          status?: Database["public"]["Enums"]["order_status"];
          subtotal?: number;
          tax_amount?: number;
          total_amount?: number;
          updated_at?: string;
        };
        Update: {
          address?: string | null;
          area_id?: string | null;
          cancelled_at?: string | null;
          cancelled_reason?: string | null;
          city_id?: string | null;
          commission_amount?: number;
          completed_at?: string | null;
          created_at?: string;
          currency?: string;
          customer_id?: string;
          deleted_at?: string | null;
          discount_amount?: number;
          id?: string;
          notes?: string | null;
          offer_id?: string | null;
          order_number?: string;
          provider_id?: string;
          provider_quote_id?: string | null;
          scheduled_at?: string | null;
          service_id?: string | null;
          status?: Database["public"]["Enums"]["order_status"];
          subtotal?: number;
          tax_amount?: number;
          total_amount?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_area_id_fkey";
            columns: ["area_id"];
            isOneToOne: false;
            referencedRelation: "areas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_city_id_fkey";
            columns: ["city_id"];
            isOneToOne: false;
            referencedRelation: "cities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_offer_id_fkey";
            columns: ["offer_id"];
            isOneToOne: false;
            referencedRelation: "offers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_provider_quote_id_fkey";
            columns: ["provider_quote_id"];
            isOneToOne: false;
            referencedRelation: "provider_quotes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "orders_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      payments: {
        Row: {
          amount: number;
          created_at: string;
          currency: string;
          gateway: string;
          gateway_payload: Json;
          gateway_reference: string | null;
          id: string;
          method: Database["public"]["Enums"]["payment_method"];
          order_id: string;
          paid_at: string | null;
          provider_id: string | null;
          refunded_amount: number;
          status: Database["public"]["Enums"]["payment_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          amount: number;
          created_at?: string;
          currency?: string;
          gateway?: string;
          gateway_payload?: Json;
          gateway_reference?: string | null;
          id?: string;
          method: Database["public"]["Enums"]["payment_method"];
          order_id: string;
          paid_at?: string | null;
          provider_id?: string | null;
          refunded_amount?: number;
          status?: Database["public"]["Enums"]["payment_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          amount?: number;
          created_at?: string;
          currency?: string;
          gateway?: string;
          gateway_payload?: Json;
          gateway_reference?: string | null;
          id?: string;
          method?: Database["public"]["Enums"]["payment_method"];
          order_id?: string;
          paid_at?: string | null;
          provider_id?: string | null;
          refunded_amount?: number;
          status?: Database["public"]["Enums"]["payment_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payments_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          bio: string | null;
          city_id: string | null;
          created_at: string;
          date_of_birth: string | null;
          display_name: string | null;
          full_name: string | null;
          gender: string | null;
          id: string;
          locale: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          avatar_url?: string | null;
          bio?: string | null;
          city_id?: string | null;
          created_at?: string;
          date_of_birth?: string | null;
          display_name?: string | null;
          full_name?: string | null;
          gender?: string | null;
          id?: string;
          locale?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          avatar_url?: string | null;
          bio?: string | null;
          city_id?: string | null;
          created_at?: string;
          date_of_birth?: string | null;
          display_name?: string | null;
          full_name?: string | null;
          gender?: string | null;
          id?: string;
          locale?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_city_id_fkey";
            columns: ["city_id"];
            isOneToOne: false;
            referencedRelation: "cities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_documents: {
        Row: {
          created_at: string;
          expires_at: string | null;
          file_url: string;
          id: string;
          notes: string | null;
          provider_id: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          status: Database["public"]["Enums"]["document_status"];
          type: Database["public"]["Enums"]["document_type"];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          expires_at?: string | null;
          file_url: string;
          id?: string;
          notes?: string | null;
          provider_id: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: Database["public"]["Enums"]["document_status"];
          type: Database["public"]["Enums"]["document_type"];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string | null;
          file_url?: string;
          id?: string;
          notes?: string | null;
          provider_id?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          status?: Database["public"]["Enums"]["document_status"];
          type?: Database["public"]["Enums"]["document_type"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "provider_documents_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "provider_documents_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_packages: {
        Row: {
          billing_interval: Database["public"]["Enums"]["billing_interval"];
          created_at: string;
          currency: string;
          description_ar: string | null;
          description_en: string | null;
          features: Json;
          id: string;
          is_active: boolean;
          max_offers: number | null;
          max_services: number | null;
          name_ar: string;
          name_en: string;
          price: number;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          billing_interval?: Database["public"]["Enums"]["billing_interval"];
          created_at?: string;
          currency?: string;
          description_ar?: string | null;
          description_en?: string | null;
          features?: Json;
          id?: string;
          is_active?: boolean;
          max_offers?: number | null;
          max_services?: number | null;
          name_ar: string;
          name_en: string;
          price: number;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          billing_interval?: Database["public"]["Enums"]["billing_interval"];
          created_at?: string;
          currency?: string;
          description_ar?: string | null;
          description_en?: string | null;
          features?: Json;
          id?: string;
          is_active?: boolean;
          max_offers?: number | null;
          max_services?: number | null;
          name_ar?: string;
          name_en?: string;
          price?: number;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      provider_quotes: {
        Row: {
          amount: number;
          created_at: string;
          currency: string;
          estimated_duration_minutes: number | null;
          id: string;
          message: string | null;
          provider_id: string;
          quote_request_id: string;
          service_id: string | null;
          status: Database["public"]["Enums"]["provider_quote_status"];
          updated_at: string;
          valid_until: string | null;
        };
        Insert: {
          amount: number;
          created_at?: string;
          currency?: string;
          estimated_duration_minutes?: number | null;
          id?: string;
          message?: string | null;
          provider_id: string;
          quote_request_id: string;
          service_id?: string | null;
          status?: Database["public"]["Enums"]["provider_quote_status"];
          updated_at?: string;
          valid_until?: string | null;
        };
        Update: {
          amount?: number;
          created_at?: string;
          currency?: string;
          estimated_duration_minutes?: number | null;
          id?: string;
          message?: string | null;
          provider_id?: string;
          quote_request_id?: string;
          service_id?: string | null;
          status?: Database["public"]["Enums"]["provider_quote_status"];
          updated_at?: string;
          valid_until?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "provider_quotes_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "provider_quotes_quote_request_id_fkey";
            columns: ["quote_request_id"];
            isOneToOne: false;
            referencedRelation: "quote_requests";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "provider_quotes_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      provider_subscriptions: {
        Row: {
          auto_renew: boolean;
          cancel_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          current_period_end: string;
          current_period_start: string;
          id: string;
          package_id: string;
          provider_id: string;
          started_at: string;
          status: Database["public"]["Enums"]["subscription_status"];
          updated_at: string;
        };
        Insert: {
          auto_renew?: boolean;
          cancel_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          current_period_end: string;
          current_period_start?: string;
          id?: string;
          package_id: string;
          provider_id: string;
          started_at?: string;
          status?: Database["public"]["Enums"]["subscription_status"];
          updated_at?: string;
        };
        Update: {
          auto_renew?: boolean;
          cancel_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          current_period_end?: string;
          current_period_start?: string;
          id?: string;
          package_id?: string;
          provider_id?: string;
          started_at?: string;
          status?: Database["public"]["Enums"]["subscription_status"];
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "provider_subscriptions_package_id_fkey";
            columns: ["package_id"];
            isOneToOne: false;
            referencedRelation: "provider_packages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "provider_subscriptions_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
        ];
      };
      providers: {
        Row: {
          area_id: string | null;
          business_name_ar: string;
          business_name_en: string;
          city_id: string | null;
          commission_rate: number;
          cover_url: string | null;
          created_at: string;
          deleted_at: string | null;
          description_ar: string | null;
          description_en: string | null;
          id: string;
          is_featured: boolean;
          logo_url: string | null;
          rating: number;
          reviews_count: number;
          slug: string;
          status: Database["public"]["Enums"]["provider_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          area_id?: string | null;
          business_name_ar: string;
          business_name_en: string;
          city_id?: string | null;
          commission_rate?: number;
          cover_url?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          id?: string;
          is_featured?: boolean;
          logo_url?: string | null;
          rating?: number;
          reviews_count?: number;
          slug: string;
          status?: Database["public"]["Enums"]["provider_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          area_id?: string | null;
          business_name_ar?: string;
          business_name_en?: string;
          city_id?: string | null;
          commission_rate?: number;
          cover_url?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          id?: string;
          is_featured?: boolean;
          logo_url?: string | null;
          rating?: number;
          reviews_count?: number;
          slug?: string;
          status?: Database["public"]["Enums"]["provider_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "providers_area_id_fkey";
            columns: ["area_id"];
            isOneToOne: false;
            referencedRelation: "areas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "providers_city_id_fkey";
            columns: ["city_id"];
            isOneToOne: false;
            referencedRelation: "cities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "providers_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      quote_items: {
        Row: {
          created_at: string;
          description: string;
          id: string;
          notes: string | null;
          quantity: number;
          quote_request_id: string;
          sort_order: number;
          unit: string | null;
        };
        Insert: {
          created_at?: string;
          description: string;
          id?: string;
          notes?: string | null;
          quantity?: number;
          quote_request_id: string;
          sort_order?: number;
          unit?: string | null;
        };
        Update: {
          created_at?: string;
          description?: string;
          id?: string;
          notes?: string | null;
          quantity?: number;
          quote_request_id?: string;
          sort_order?: number;
          unit?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "quote_items_quote_request_id_fkey";
            columns: ["quote_request_id"];
            isOneToOne: false;
            referencedRelation: "quote_requests";
            referencedColumns: ["id"];
          },
        ];
      };
      quote_requests: {
        Row: {
          area_id: string | null;
          attachments: Json;
          budget_max: number | null;
          budget_min: number | null;
          category_id: string;
          city_id: string | null;
          created_at: string;
          currency: string;
          customer_id: string;
          deleted_at: string | null;
          description: string | null;
          expires_at: string | null;
          id: string;
          preferred_date: string | null;
          status: Database["public"]["Enums"]["quote_request_status"];
          sub_category_id: string | null;
          title: string;
          updated_at: string;
        };
        Insert: {
          area_id?: string | null;
          attachments?: Json;
          budget_max?: number | null;
          budget_min?: number | null;
          category_id: string;
          city_id?: string | null;
          created_at?: string;
          currency?: string;
          customer_id: string;
          deleted_at?: string | null;
          description?: string | null;
          expires_at?: string | null;
          id?: string;
          preferred_date?: string | null;
          status?: Database["public"]["Enums"]["quote_request_status"];
          sub_category_id?: string | null;
          title: string;
          updated_at?: string;
        };
        Update: {
          area_id?: string | null;
          attachments?: Json;
          budget_max?: number | null;
          budget_min?: number | null;
          category_id?: string;
          city_id?: string | null;
          created_at?: string;
          currency?: string;
          customer_id?: string;
          deleted_at?: string | null;
          description?: string | null;
          expires_at?: string | null;
          id?: string;
          preferred_date?: string | null;
          status?: Database["public"]["Enums"]["quote_request_status"];
          sub_category_id?: string | null;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quote_requests_area_id_fkey";
            columns: ["area_id"];
            isOneToOne: false;
            referencedRelation: "areas";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quote_requests_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quote_requests_city_id_fkey";
            columns: ["city_id"];
            isOneToOne: false;
            referencedRelation: "cities";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quote_requests_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quote_requests_sub_category_id_fkey";
            columns: ["sub_category_id"];
            isOneToOne: false;
            referencedRelation: "sub_categories";
            referencedColumns: ["id"];
          },
        ];
      };
      reviews: {
        Row: {
          comment: string | null;
          created_at: string;
          customer_id: string;
          deleted_at: string | null;
          id: string;
          order_id: string | null;
          provider_id: string;
          provider_replied_at: string | null;
          provider_reply: string | null;
          rating: number;
          service_id: string | null;
          status: Database["public"]["Enums"]["review_status"];
          title: string | null;
          updated_at: string;
        };
        Insert: {
          comment?: string | null;
          created_at?: string;
          customer_id: string;
          deleted_at?: string | null;
          id?: string;
          order_id?: string | null;
          provider_id: string;
          provider_replied_at?: string | null;
          provider_reply?: string | null;
          rating: number;
          service_id?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          title?: string | null;
          updated_at?: string;
        };
        Update: {
          comment?: string | null;
          created_at?: string;
          customer_id?: string;
          deleted_at?: string | null;
          id?: string;
          order_id?: string | null;
          provider_id?: string;
          provider_replied_at?: string | null;
          provider_reply?: string | null;
          rating?: number;
          service_id?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          title?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reviews_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: true;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reviews_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      service_images: {
        Row: {
          alt_ar: string | null;
          alt_en: string | null;
          created_at: string;
          id: string;
          is_primary: boolean;
          service_id: string;
          sort_order: number;
          url: string;
        };
        Insert: {
          alt_ar?: string | null;
          alt_en?: string | null;
          created_at?: string;
          id?: string;
          is_primary?: boolean;
          service_id: string;
          sort_order?: number;
          url: string;
        };
        Update: {
          alt_ar?: string | null;
          alt_en?: string | null;
          created_at?: string;
          id?: string;
          is_primary?: boolean;
          service_id?: string;
          sort_order?: number;
          url?: string;
        };
        Relationships: [
          {
            foreignKeyName: "service_images_service_id_fkey";
            columns: ["service_id"];
            isOneToOne: false;
            referencedRelation: "services";
            referencedColumns: ["id"];
          },
        ];
      };
      services: {
        Row: {
          base_price: number;
          category_id: string;
          created_at: string;
          currency: string;
          deleted_at: string | null;
          description_ar: string | null;
          description_en: string | null;
          duration_minutes: number | null;
          id: string;
          is_featured: boolean;
          price_type: Database["public"]["Enums"]["price_type"];
          provider_id: string;
          rating: number;
          reviews_count: number;
          slug: string;
          status: Database["public"]["Enums"]["service_status"];
          sub_category_id: string | null;
          title_ar: string;
          title_en: string;
          updated_at: string;
        };
        Insert: {
          base_price?: number;
          category_id: string;
          created_at?: string;
          currency?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          duration_minutes?: number | null;
          id?: string;
          is_featured?: boolean;
          price_type?: Database["public"]["Enums"]["price_type"];
          provider_id: string;
          rating?: number;
          reviews_count?: number;
          slug: string;
          status?: Database["public"]["Enums"]["service_status"];
          sub_category_id?: string | null;
          title_ar: string;
          title_en: string;
          updated_at?: string;
        };
        Update: {
          base_price?: number;
          category_id?: string;
          created_at?: string;
          currency?: string;
          deleted_at?: string | null;
          description_ar?: string | null;
          description_en?: string | null;
          duration_minutes?: number | null;
          id?: string;
          is_featured?: boolean;
          price_type?: Database["public"]["Enums"]["price_type"];
          provider_id?: string;
          rating?: number;
          reviews_count?: number;
          slug?: string;
          status?: Database["public"]["Enums"]["service_status"];
          sub_category_id?: string | null;
          title_ar?: string;
          title_en?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "services_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "services_provider_id_fkey";
            columns: ["provider_id"];
            isOneToOne: false;
            referencedRelation: "providers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "services_sub_category_id_fkey";
            columns: ["sub_category_id"];
            isOneToOne: false;
            referencedRelation: "sub_categories";
            referencedColumns: ["id"];
          },
        ];
      };
      settings: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          is_public: boolean;
          key: string;
          updated_at: string;
          value: Json;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          is_public?: boolean;
          key: string;
          updated_at?: string;
          value?: Json;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          is_public?: boolean;
          key?: string;
          updated_at?: string;
          value?: Json;
        };
        Relationships: [];
      };
      sub_categories: {
        Row: {
          category_id: string;
          created_at: string;
          deleted_at: string | null;
          id: string;
          is_active: boolean;
          name_ar: string;
          name_en: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          category_id: string;
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          is_active?: boolean;
          name_ar: string;
          name_en: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          category_id?: string;
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          is_active?: boolean;
          name_ar?: string;
          name_en?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sub_categories_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
        ];
      };
      transactions: {
        Row: {
          amount: number;
          balance_after: number | null;
          created_at: string;
          currency: string;
          id: string;
          metadata: Json;
          order_id: string | null;
          payment_id: string | null;
          reference: string | null;
          status: Database["public"]["Enums"]["transaction_status"];
          type: Database["public"]["Enums"]["transaction_type"];
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          amount: number;
          balance_after?: number | null;
          created_at?: string;
          currency?: string;
          id?: string;
          metadata?: Json;
          order_id?: string | null;
          payment_id?: string | null;
          reference?: string | null;
          status?: Database["public"]["Enums"]["transaction_status"];
          type: Database["public"]["Enums"]["transaction_type"];
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          amount?: number;
          balance_after?: number | null;
          created_at?: string;
          currency?: string;
          id?: string;
          metadata?: Json;
          order_id?: string | null;
          payment_id?: string | null;
          reference?: string | null;
          status?: Database["public"]["Enums"]["transaction_status"];
          type?: Database["public"]["Enums"]["transaction_type"];
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "transactions_order_id_fkey";
            columns: ["order_id"];
            isOneToOne: false;
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "transactions_payment_id_fkey";
            columns: ["payment_id"];
            isOneToOne: false;
            referencedRelation: "payments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "transactions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      users: {
        Row: {
          created_at: string;
          deleted_at: string | null;
          email: string | null;
          id: string;
          is_verified: boolean;
          last_sign_in_at: string | null;
          phone: string | null;
          role: Database["public"]["Enums"]["user_role"];
          status: Database["public"]["Enums"]["user_status"];
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          deleted_at?: string | null;
          email?: string | null;
          id: string;
          is_verified?: boolean;
          last_sign_in_at?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          status?: Database["public"]["Enums"]["user_status"];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          deleted_at?: string | null;
          email?: string | null;
          id?: string;
          is_verified?: boolean;
          last_sign_in_at?: string | null;
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          status?: Database["public"]["Enums"]["user_status"];
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      current_provider_id: { Args: never; Returns: string };
      current_user_role: {
        Args: never;
        Returns: Database["public"]["Enums"]["user_role"];
      };
      is_admin: { Args: never; Returns: boolean };
      is_provider_owner: { Args: { p_provider_id: string }; Returns: boolean };
      recalc_provider_rating: {
        Args: { p_provider_id: string };
        Returns: undefined;
      };
      recalc_service_rating: {
        Args: { p_service_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      billing_interval: "monthly" | "quarterly" | "yearly";
      conversation_status: "open" | "closed" | "archived";
      coupon_status: "active" | "inactive" | "expired";
      discount_type: "percentage" | "fixed_amount";
      document_status: "pending" | "approved" | "rejected";
      document_type:
        | "civil_id"
        | "commercial_license"
        | "signature_authorization"
        | "tax_certificate"
        | "other";
      notification_channel: "in_app" | "email" | "sms" | "push" | "whatsapp";
      notification_type:
        | "order"
        | "quote"
        | "message"
        | "review"
        | "payment"
        | "system"
        | "promotion";
      offer_status: "draft" | "scheduled" | "active" | "expired" | "inactive";
      order_status:
        | "pending"
        | "confirmed"
        | "in_progress"
        | "completed"
        | "cancelled"
        | "refunded"
        | "disputed";
      payment_method:
        | "knet"
        | "visa"
        | "mastercard"
        | "apple_pay"
        | "google_pay"
        | "wallet"
        | "cash";
      payment_status:
        "pending" | "paid" | "failed" | "refunded" | "partially_refunded";
      price_type: "fixed" | "starting_from" | "hourly" | "quote";
      provider_quote_status:
        "submitted" | "accepted" | "rejected" | "withdrawn" | "expired";
      provider_status: "pending" | "verified" | "rejected" | "suspended";
      quote_request_status:
        "open" | "quoted" | "accepted" | "closed" | "cancelled" | "expired";
      review_status: "published" | "pending" | "hidden";
      service_status: "draft" | "active" | "inactive" | "archived";
      subscription_status:
        "trialing" | "active" | "past_due" | "cancelled" | "expired";
      transaction_status: "pending" | "completed" | "failed" | "reversed";
      transaction_type:
        | "charge"
        | "refund"
        | "payout"
        | "commission"
        | "wallet_topup"
        | "wallet_withdrawal";
      user_role: "admin" | "provider" | "customer";
      user_status: "active" | "suspended" | "pending" | "banned";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      billing_interval: ["monthly", "quarterly", "yearly"],
      conversation_status: ["open", "closed", "archived"],
      coupon_status: ["active", "inactive", "expired"],
      discount_type: ["percentage", "fixed_amount"],
      document_status: ["pending", "approved", "rejected"],
      document_type: [
        "civil_id",
        "commercial_license",
        "signature_authorization",
        "tax_certificate",
        "other",
      ],
      notification_channel: ["in_app", "email", "sms", "push", "whatsapp"],
      notification_type: [
        "order",
        "quote",
        "message",
        "review",
        "payment",
        "system",
        "promotion",
      ],
      offer_status: ["draft", "scheduled", "active", "expired", "inactive"],
      order_status: [
        "pending",
        "confirmed",
        "in_progress",
        "completed",
        "cancelled",
        "refunded",
        "disputed",
      ],
      payment_method: [
        "knet",
        "visa",
        "mastercard",
        "apple_pay",
        "google_pay",
        "wallet",
        "cash",
      ],
      payment_status: [
        "pending",
        "paid",
        "failed",
        "refunded",
        "partially_refunded",
      ],
      price_type: ["fixed", "starting_from", "hourly", "quote"],
      provider_quote_status: [
        "submitted",
        "accepted",
        "rejected",
        "withdrawn",
        "expired",
      ],
      provider_status: ["pending", "verified", "rejected", "suspended"],
      quote_request_status: [
        "open",
        "quoted",
        "accepted",
        "closed",
        "cancelled",
        "expired",
      ],
      review_status: ["published", "pending", "hidden"],
      service_status: ["draft", "active", "inactive", "archived"],
      subscription_status: [
        "trialing",
        "active",
        "past_due",
        "cancelled",
        "expired",
      ],
      transaction_status: ["pending", "completed", "failed", "reversed"],
      transaction_type: [
        "charge",
        "refund",
        "payout",
        "commission",
        "wallet_topup",
        "wallet_withdrawal",
      ],
      user_role: ["admin", "provider", "customer"],
      user_status: ["active", "suspended", "pending", "banned"],
    },
  },
} as const;
